FROM --platform=$BUILDPLATFORM golang:1.18-bullseye AS build
ARG TARGETARCH
ARG TARGETOS
ARG BUILD_VERSION
ENV BINARY_PATH="/pibox-framebuffer-${TARGETOS}-${TARGETARCH}-v${BUILD_VERSION}"

ENV APP_HOME /go/src/pibox-framebuffer
WORKDIR "$APP_HOME"

COPY . .

RUN go mod download
RUN go mod verify
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -ldflags="-s -w" -o "${BINARY_PATH}"

FROM scratch
ARG TARGETARCH
ARG TARGETOS
ARG BUILD_VERSION
ENV BINARY_PATH="/pibox-framebuffer-${TARGETOS}-${TARGETARCH}-v${BUILD_VERSION}"

COPY --from=build "${BINARY_PATH}" /
